services:
  - type: web
    name: bridgex-api
    runtime: node
    plan: free
    rootDir: relayer
    buildCommand: npm run build
    startCommand: npm run start:web

  - type: worker
    name: bridgex-worker
    runtime: node
    plan: free
    rootDir: relayer
    buildCommand: npm run build
    startCommand: npm run start:worker
